@HostAddress = https://localhost:7152
# ID пользователя, с которым будем работать (должен существовать в базе)
@UserId = be2b3042-1c71-4c36-a1b6-feeb1a1fdba2
# JWT Токен (получите его через /authentication/login или /authentication/register)
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGlubm9zaG9wLmNvbSIsImlkIjoiMWI5ZTU0NGQtZjczMy00ZDczLWFmNWItN2QyMzgyNDQ4YzllIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIkFkbWluIiwiVmVyaWZpZWQiXSwicGVybWlzc2lvbnMiOlsidXNlcjpyZWFkIiwidXNlcjpkZWxldGUiLCJwcm9maWxlOmNyZWF0ZSIsInByb2ZpbGU6dXBkYXRlIiwicHJvZmlsZTpyZWFkIiwicHJvZmlsZTphY3RpdmF0ZSIsInByb2ZpbGU6ZGVhY3RpdmF0ZSIsInJldmlldzpjcmVhdGUiLCJyZXZpZXc6cmVhZCIsInJldmlldzpkZWxldGUiLCJyZXZpZXc6dXBkYXRlIiwicHJvZHVjdDpjcmVhdGUiLCJwcm9kdWN0OnJlYWQiLCJwcm9kdWN0OnVwZGF0ZSIsInByb2R1Y3Q6ZGVsZXRlIl0sImV4cCI6MTc2NDU0NTEyOSwiaXNzIjoiSW5ub1Nob3AiLCJhdWQiOiJJbm5vU2hvcCJ9.HyftOEnSDtl3l4LG5wO6q9M7D_lahl5UuOFqY2Msbm4

### 1. Получить информацию о пользователе (основная инфа + профиль, если есть)
GET {{HostAddress}}/api/v1/users/{{UserId}}
Authorization: Bearer {{Token}}
Accept: application/json

###

### 2. Создать профиль пользователя
# Примечание: Country должно соответствовать списку AllowedCountries (например, "Belarus")
POST {{HostAddress}}/api/v1/users/{{UserId}}/profile
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "firstName": "Ivan",
  "lastName": "Ivanov",
  "avatarUrl": "https://i.pinimg.com/736x/c8/cc/24/c8cc24bba37a25c009647b8875aae0e3.jpg",
  "phoneNumber": "+375291234567",
  "country": "Belarus",
  "state": "Minsk Region",
  "city": "Minsk"
}

###

### 3. Получить профиль пользователя (только данные профиля)
GET {{HostAddress}}/api/v1/users/{{UserId}}/profile
Authorization: Bearer {{Token}}
Accept: application/json

###

### 4. Обновить профиль пользователя
# Можно передавать только те поля, которые нужно изменить (nullable)
PUT {{HostAddress}}/api/v1/users/{{UserId}}/profile
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "firstName": "Полина",
  "lastName": "Мельянцева",
  "city": "Витебск",
  "phoneNumber": "+375299876543"
}

###


### 5. Деактивировать пользователя (только для админа)
POST {{HostAddress}}/api/v1/users/{{UserId}}/deactivate
Authorization: Bearer {{Token}}
Content-Type: application/json

###

### 6. Активировать пользователя (только для админа)
POST {{HostAddress}}/api/v1/users/{{UserId}}/activate
Authorization: Bearer {{Token}}
Content-Type: application/json
