@HostAddress = https://localhost:7152
# ID пользователя, с которым будем работать (должен существовать в базе)
@UserId = 10191f52-e1da-4163-ab00-c4d3c017c159
# JWT Токен (получите его через /authentication/login или /authentication/register)
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwiaWQiOiIxMDE5MWY1Mi1lMWRhLTQxNjMtYWIwMC1jNGQzYzAxN2MxNTkiLCJleHAiOjE3NjQ0NDEyMTcsImlzcyI6Iklubm9TaG9wIiwiYXVkIjoiSW5ub1Nob3AifQ.GHqWNc_-F-YLFdIhLrFYRRDkVFfleSYVUo430MtgYsc

### 1. Получить информацию о пользователе (основная инфа + профиль, если есть)
GET {{HostAddress}}/api/v1/users/{{UserId}}
Authorization: Bearer {{Token}}
Accept: application/json

###

### 2. Создать профиль пользователя
# Примечание: Country должно соответствовать списку AllowedCountries (например, "Belarus")
POST {{HostAddress}}/api/v1/users/{{UserId}}/profile
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "firstName": "Ivan",
  "lastName": "Ivanov",
  "avatarUrl": "https://i.pinimg.com/736x/c8/cc/24/c8cc24bba37a25c009647b8875aae0e3.jpg",
  "phoneNumber": "+375291234567",
  "country": "Belarus",
  "state": "Minsk Region",
  "city": "Minsk"
}

###

### 3. Получить профиль пользователя (только данные профиля)
GET {{HostAddress}}/api/v1/users/{{UserId}}/profile
Authorization: Bearer {{Token}}
Accept: application/json

###

### 4. Обновить профиль пользователя
# Можно передавать только те поля, которые нужно изменить (nullable)
PUT {{HostAddress}}/api/v1/users/{{UserId}}/profile
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "firstName": "Dmitry",
  "lastName": "Ivanov",
  "city": "Grodno",
  "phoneNumber": "+375299876543"
}

###


### 5. Деактивировать пользователя (только для админа)
POST {{HostAddress}}/api/v1/users/{{UserId}}/deactivate
Authorization: Bearer {{Token}}
Content-Type: application/json

###

### 6. Активировать пользователя (только для админа)
POST {{HostAddress}}/api/v1/users/{{UserId}}/activate
Authorization: Bearer {{Token}}
Content-Type: application/json
