@HostAddress = https://localhost:7152
# ID пользователя, КОТОРОМУ оставляем отзыв (Продавец)
@TargetUserId = 4028c0ec-4451-4277-9e6d-1c8178fb842f

# ID отзыва (заполняется после создания)
@ReviewId = caa8909a-ce0c-40ff-a6c4-ff503b2fe100

# Токен АВТОРА отзыва (Покупателя).
# Важно: Автор не может быть тем же человеком, что и TargetUserId (согласно логике домена)
@Token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwiaWQiOiJiNzMxZDcwNi0zMjIwLTRkZGQtYWNmZS0zOWZkNGJjYzc2OTUiLCJleHAiOjE3NjQ1MDg5OTgsImlzcyI6Iklubm9TaG9wIiwiYXVkIjoiSW5ub1Nob3AifQ.6_fheOySOh7ftqdvUNYp7gZz4RYOZg3dmtiIPVq7PrE
### 1. Создать отзыв
# Рейтинг от 1 до 5. Комментарий обязателен
POST {{HostAddress}}/api/v1/users/{{TargetUserId}}/reviews
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "rating": 5,
  "comment": "Отличный продавец, товар соответствует описанию! Рекомендую."
}

###

### 2. Получить список отзывов пользователя (с пагинацией)
GET {{HostAddress}}/api/v1/users/{{TargetUserId}}/reviews?page=1&pageSize=10
Authorization: Bearer {{Token}}
Accept: application/json

###

### 3. Получить конкретный отзыв по ID
GET {{HostAddress}}/api/v1/users/{{TargetUserId}}/reviews/{{ReviewId}}
Authorization: Bearer {{Token}}
Accept: application/json

###

### 4. Обновить отзыв
# Изменять отзыв может только его автор (или админ, если настроены политики)
PUT {{HostAddress}}/api/v1/users/{{TargetUserId}}/reviews/{{ReviewId}}
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "rating": 1,
  "comment": "Все хорошо, но доставка немного задержалась. Изменил оценку."
}

###

### 5. Удалить отзыв
# Удалять может автор или админ
DELETE {{HostAddress}}/api/v1/users/{{TargetUserId}}/reviews/{{ReviewId}}
Authorization: Bearer {{Token}}