@HostAddress = https://localhost:7152

### 1. Request password reset
POST {{HostAddress}}/authentication/forgot-password
Content-Type: application/json

{
  "email": "test1@test.com"
}

### 2. Reset password (Get token from Mailpit: http://localhost:8025)
POST {{HostAddress}}/authentication/reset-password
Content-Type: application/json

{
  "email": "test1@test.com",
  "token": "4zgIyJWP2b-nEZSWGSJpESF3bXcg5otApY_17QxrayI",
  "newPassword": "NewStrongPassword123!"
}

