#@host = localhost:7152

POST http://localhost:5095/authentication/login
#POST https://{{host}}/authentication/login
Content-Type: application/json

{
  "email": "admin@innoshop.com",
  "password": "Admin123!@#"
}
