@host = localhost:7152
@userId = d6ff4c69-488c-429e-ad87-41eb2616fc68
@token = 4609ecb9-438d-4624-9a2f-6b3e2edfee5c


GET https://{{host}}/Authentication/verify-email?userId={{userId}}&token={{token}}

# Пример использования:
# 1. Откройте mailpit и найдите письмо с verify-ссылкой.
# 2. Извлеките userId и token из URL в письме.
# 3. Подставьте в @userId и @token выше.
# 4. Кликните "Send Request" над этим блоком.