@host = localhost:7152
@userId = b731d706-3220-4ddd-acfe-39fd4bcc7695
@token = 15947feb-d4ba-4f7c-8a31-c83ff626a56c


GET https://{{host}}/Authentication/verify-email?userId={{userId}}&token={{token}}

# Пример использования:
# 1. Откройте mailpit и найдите письмо с verify-ссылкой.
# 2. Извлеките userId и token из URL в письме.
# 3. Подставьте в @userId и @token выше.
# 4. Кликните "Send Request" над этим блоком.